### ISSUE TITLE
Error in loading the model

### ISSUE THREAD

**Issue by ohata20** [ivyha010/AttendAffectNet#2]
Thank you for uploading the code!

On runnnig AttendAffectNet/test/test_model_Feature_AAN_video.py，
I get a ModuleNotFoundError，when loading the model
model = torch.load(os.path.join(model_path, model_name))
->ModuleNotFoundError: No module named 'model_1_only_video_Pooling'

Would you be kind enough to check this from your side ?

I believe it is coused by using pickle to load the model.
Could you upload the  pre-trained model state_dict()?

**Comment by theodumont** [comment]
Hey, another user of the repo here!
Thanks @ivyha010  for uploading the code indeed.

@ohata20, the hacky workaround I used to run the code is to rename `model_Feature_AAN_only_video_Pooling.py` into `model_1_only_video_Pooling.py`, and replace the line
```python
from model_Feature_AAN_only_video_Pooling import *
```
by
```python
from model_1_only_video_Pooling import *
```
in `test_model_Feature_AAN_video.py`.

It should let you run the code if I'm not mistaken - but maybe there is a more elegant way of solving this.

**Comment by ohata20** [comment]
I was able to avoid this error by the method taught by @theodumont .
